### ISSUE TITLE
Condicion de carrera gateway

### ISSUE THREAD

**Issue by JulianGCalderon** [JulianGCalderon-FIUBA/distribuidos-tp1#19]
Si dos clientes se conectan al mismo tiempo, es posible que tengan el mismo ID.
1. Cliente 1 se conecta
2. Se incrementa el clientID
3. Cliente 2 se conecta
4. Se incrementa el clientID
5. Cliente 1/2 entran al clientHandler, ambos con clientID = 2.

Creo que tendriamos que incrementarlo cuando se acepta el cliente, y pasarle el id a la gorutine de handleClient.

No es prioritario, podemos dejarlo para cuando terminemos / la proxima entrega, ya que no se rompe ahora.

**Comment by solmoon16** [comment]
creo que esto lo cambiaste ya en tu refactor

**Comment by JulianGCalderon** [comment]
Ah jajaj no me acoredaba. Lo cierro entonces
