### ISSUE TITLE
Investigar uso de disco

### ISSUE THREAD

**Issue by JulianGCalderon** [JulianGCalderon-FIUBA/distribuidos-tp1#72]
No necesariamente implementarlo, pero hay que investigar esto.

Hay 2 motivos principales para bajar a disco: 
- Reducir uso de memoria RAM
- Asegurar tolerancia a fallas

Para la proxima entrega nos interesa el primero, pero el segundo tambien tenemos que tenerlo en cuenta. 

En primer lugar, investigaria:
- Que nodos requieren uso del disco (cuales gastan mas memoria)
- Como implementar esa persistencia:
  - Formato binario del archivo
  - Se serializa despues de cada batch, o despues de n batches?
  - Como hacer para que no sea terriblemente lento?
    - Se puede shardear los archivos a escribir segun algun valor? 
    - Hay algun formato que minimiza cantidad de escrituras?
    - Se puede usar paralelismo para cada archivo?

**Comment by rplatini** [comment]
### Nodos con mayor uso de disco

Investigando con `docker stat`

- language-filter →supongo porque se acumulan todos los mensajes en los nodos, no es porque guarde estado
- group-by
- percentile → si bien con este comando no parece utilizar demasiada memoria, creo que se guardan todos los juegos para hacer el cálculo (no estoy segura)

### Algunas ideas

Por ahora, creo que solo tiene sentido bajar a disco el estado de `group-by`.

Podemos tener una especie de **cache** de juegos, donde se tengan en memoria los juegos con mayor frecuencia de acceso, es decir, los que tienen mayor cantidad de reviews.

Ahora bien, bajar a disco es un trade offer entre disminuir el uso de memoria sacrificando performance, entonces es importante llegar a un equilibrio entre esto. En el peor de los casos,  podríamos tener 1 review para cada juego, entonces en este caso no estaríamos optimizando nada la memoria. En el mejor de los casos, podríamos tener unos pocos juegos para mucha cantidad de reviews, y sería optimo ya que los juegos más frecuentados siempre se accederían en memoria. Entonces, ¿cómo determinar la cantidad de juegos a guardar en memoria?

Podríamos mandar la cantidad de juegos y reviews en el header de los batches. Sabiendo que tenemos N juegos y M reviews, podemos calcular el promedio de reviews por juego. Entonces, los elementos a guardar en memoria podrian ser todos los que tienen cantidad de reviews mayor al promedio. Si esto es una cantidad muy grande, podemos establecer un porcentaje. 

Haciendo esto, la cantidad de elementos que tenemos en memoria es agnóstica a los datos que envíe el cliente.

### Escritura en disco

Los datos se serializarán y se guardan como `GameStat`

Podemos definir un threshold de líneas por archivo, entonces en base a la cantidad de juegos que vamos a recibir podemos crear los archivos suficientes para que no sea extremadamente lento buscar un `app_id`. 

Habría que pensar un criterio de búsqueda para saber en qué archivo se encuentra un `app_id`. Si sabemos el archivo, después podemos usar búsqueda binaria.
