### ISSUE TITLE
Reordenar gateway para soportar multiples clientes

### ISSUE THREAD

**Issue by JulianGCalderon** [JulianGCalderon-FIUBA/distribuidos-tp1#73]
Ya lo esta haciendo @solmoon16, pero lo anoto igualmente:

- Verificar que el gateway este efectivamente preparado para soportar multiples clientes.
- Mover la logica de la conexion con el cliente al request/connection handler
- Usar una cola por resultado, o una cola para todos los resultados?

**Comment by solmoon16** [comment]
yo creo que lo mejor es tener una cola para todos los resultados, y como el results handler por debajo usa al nodo del middleware desde ahí hay que pasarle el client id de cada batch al results handler para que sepa a qué channel mandarlo. Con eso creo que bastaría para que funcione para múltiples clientes
